# Generated by Django 6.0.6 on 2026-09-07 04:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0022_companysupplier_accepted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invitations', to='account.company')),
                ('company_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='account.companysupplier')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_supplier_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supplier_invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='supplier_invoices/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='submitted', max_length=20)),
                ('procurement_comments', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoices', to='account.company')),
                ('company_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='account.companysupplier')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_supplier_invoices', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_supplier_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supplier_invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
