# Generated by Django 6.0.6 on 2026-07-04 05:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rfi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rfi',
            name='trade',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.CreateModel(
            name='RFIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('document_url', models.URLField(blank=True, max_length=500, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfi_messages', to=settings.AUTH_USER_MODEL)),
                ('rfi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='employee.rfi')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
