# Generated by Django 6.0.6 on 2026-07-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_dailybriefing_rams_todolist_toolboxtalk'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybriefing',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailybriefing',
            name='signed_document_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='rams',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rams',
            name='signed_document_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='signed_document_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='toolboxtalk',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolboxtalk',
            name='signed_document_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
