# Generated by Django 6.0.6 on 2026-07-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_dailybriefing_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybriefing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rams',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolboxtalk',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
