# Generated by Django 6.0.6 on 2026-07-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_dailybriefing_description_rams_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfi',
            name='assigned_to_technical_department',
            field=models.BooleanField(default=False),
        ),
    ]
