# Generated by Django 6.0.6 on 2026-07-02 06:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_admin', '0004_labourbooking_loadingclearingbooking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaNR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('material_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proformas', to='project_admin.project')),
            ],
            options={
                'db_table': 'proforma_nrs',
            },
        ),
    ]
