from django.urls import path
from .views import (
    ProjectListCreateView, 
    ProjectDetailView, 
    ProjectRoleAssignmentsView, 
    CompanyUsersView, 
    ProjectFoldersView,
    ProjectFoldersBulkUpdateView,
    ProjectApprovalConfigurationsView,
    MyProjectsView,
    ProjectFinancialBreakdownView,
    DashboardRFIListView,
    RFICloseView,
    RFIMessageCreateView,
    ProformaAccessListView,
    ProformaAccessDetailView,
    LoadingClearingAccessListView,
    LoadingClearingAccessDetailView,
)
from .invoice_views import (
    UserInvoiceListView,
    UserInvoiceApproveView,
    UserInvoicePayView,
    UserInvoiceCommercialCommentView,
    BucketListView,
    BucketSubmitView,
)

urlpatterns = [
    path("users/", CompanyUsersView.as_view(), name="company-users"),
    path("my-projects/", MyProjectsView.as_view(), name="my-projects"),
    path("projects/", ProjectListCreateView.as_view(), name="project-list-create"),
    path("projects/<uuid:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path("projects/<uuid:pk>/roles/", ProjectRoleAssignmentsView.as_view(), name="project-roles"),
    path("projects/<uuid:pk>/folders/", ProjectFoldersView.as_view(), name="project-folders"),
    path("projects/<uuid:pk>/folders/bulk-update/", ProjectFoldersBulkUpdateView.as_view(), name="project-folders-bulk-update"),
    path("projects/<uuid:pk>/approval-configs/", ProjectApprovalConfigurationsView.as_view(), name="project-approval-configs"),
    path("projects/<uuid:pk>/financial-breakdown/", ProjectFinancialBreakdownView.as_view(), name="project-financial-breakdown"),
    path("rfis/", DashboardRFIListView.as_view(), name="dashboard-rfi-list"),
    path("rfis/<uuid:pk>/close/", RFICloseView.as_view(), name="dashboard-rfi-close"),
    path("rfis/<uuid:pk>/messages/", RFIMessageCreateView.as_view(), name="dashboard-rfi-messages"),
    path("projects/<uuid:pk>/proforma-access/", ProformaAccessListView.as_view(), name="project-proforma-access"),
    path("projects/<uuid:pk>/proforma-access/<uuid:access_pk>/", ProformaAccessDetailView.as_view(), name="project-proforma-access-detail"),
    path("projects/<uuid:pk>/loading-clearing-access/", LoadingClearingAccessListView.as_view(), name="project-loading-clearing-access"),
    path("projects/<uuid:pk>/loading-clearing-access/<uuid:access_pk>/", LoadingClearingAccessDetailView.as_view(), name="project-loading-clearing-access-detail"),
    # ── User Invoices ──
    path("user-invoices/", UserInvoiceListView.as_view(), name="user-invoice-list"),
    path("user-invoices/<uuid:invoice_id>/approve/", UserInvoiceApproveView.as_view(), name="user-invoice-approve"),
    path("user-invoices/<uuid:invoice_id>/pay/", UserInvoicePayView.as_view(), name="user-invoice-pay"),
    path("user-invoices/<uuid:invoice_id>/commercial-comment/", UserInvoiceCommercialCommentView.as_view(), name="user-invoice-commercial-comment"),
    path("bucket/", BucketListView.as_view(), name="bucket-list"),
    path("bucket/submit/", BucketSubmitView.as_view(), name="bucket-submit"),
]
