# Generated by Django 6.0.6 on 2026-06-25 03:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_alter_useraccount_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=255)),
                ('job_code', models.CharField(max_length=100)),
                ('vat_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('project_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('material_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('labour_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prelims_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_projects', to='account.company')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company'], name='projects_company_408096_idx'), models.Index(fields=['job_code'], name='projects_job_cod_fef709_idx'), models.Index(fields=['is_completed'], name='projects_is_comp_595d58_idx')],
            },
        ),
    ]
