# Generated by Django 6.0.6 on 2026-06-28 05:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='monthly_application_date',
            field=models.PositiveIntegerField(default=1, help_text='Day of the month the new application period starts (1-31).'),
        ),
        migrations.CreateModel(
            name='ApprovalConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('user_invoice', 'User Invoices'), ('supplier_invoice', 'Supplier Invoices'), ('variations', 'Variations'), ('purchase_order', 'Purchase Orders'), ('proforma', 'Proforma Nr Invoices')], max_length=50)),
                ('condition_value', models.CharField(default='ALL', max_length=50)),
                ('required_roles', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_configs', to='project_admin.project')),
            ],
            options={
                'db_table': 'approval_configurations',
            },
        ),
        migrations.CreateModel(
            name='ProjectFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Electrical, Plumbing', max_length=255)),
                ('is_management', models.BooleanField(default=False, help_text='If this is a special management prelims folder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='project_admin.project')),
            ],
            options={
                'db_table': 'project_folders',
            },
        ),
        migrations.CreateModel(
            name='ProjectSubfolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Work Area', max_length=255)),
                ('project_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('labour_target', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='project_admin.projectfolder')),
            ],
            options={
                'db_table': 'project_subfolders',
            },
        ),
        migrations.CreateModel(
            name='FolderAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hide_labour_target', models.BooleanField(default=False)),
                ('is_management_assignment', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_assignments', to=settings.AUTH_USER_MODEL)),
                ('subfolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='project_admin.projectsubfolder')),
            ],
            options={
                'db_table': 'folder_assignments',
            },
        ),
    ]
