# Generated by Django 6.0.6 on 2026-06-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0002_project_monthly_application_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubfolder',
            name='rows',
            field=models.JSONField(default=list, help_text='Stores the datagrid rows for this subfolder'),
        ),
    ]
