# Generated by Django 6.0.6 on 2026-07-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0005_projectvaluebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalconfiguration',
            name='toggle_states',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='approvalconfiguration',
            name='action_type',
            field=models.CharField(choices=[('user_invoice', 'User Invoices'), ('supplier_invoice', 'Supplier Invoices'), ('variations', 'Variations'), ('purchase_order', 'Purchase Orders'), ('proforma', 'Proforma Nr Invoices'), ('user_variations_invoice', 'User Variations Invoices')], max_length=50),
        ),
    ]
