# Generated by Django 6.0.6 on 2026-07-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0008_loadingclearingaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadingclearingaccess',
            name='is_paused',
        ),
        migrations.RemoveField(
            model_name='proformaaccess',
            name='is_paused',
        ),
        migrations.AddField(
            model_name='loadingclearingaccess',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proformaaccess',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
