# Generated by Django 6.0.6 on 2026-07-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0009_remove_loadingclearingaccess_is_paused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderassignment',
            name='employee_labour_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
