# Generated by Django 6.0.6 on 2026-07-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0011_loadingclearingbooking_money_on_hold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadingclearingbooking',
            name='money_on_hold',
        ),
        migrations.AddField(
            model_name='loadingclearingbooking',
            name='attachment_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='loadingclearingbooking',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
