# Generated by Django 6.0.6 on 2026-07-11 03:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0012_remove_loadingclearingbooking_money_on_hold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationsAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations_accesses', to='project_admin.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'variations_accesses',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
