# Generated by Django 6.0.6 on 2026-07-13 05:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0013_variationsaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('source_type', models.CharField(choices=[('variation', 'Variation'), ('labour_target', 'Labour Target'), ('proforma', 'Proforma NR'), ('loading_clearing', 'Loading & Clearing')], max_length=30)),
                ('source_id', models.CharField(blank=True, default='', max_length=100)),
                ('variation_sheet_no', models.CharField(blank=True, default='', max_length=50)),
                ('proforma_no', models.CharField(blank=True, default='', max_length=50)),
                ('work_area', models.CharField(blank=True, default='', max_length=255)),
                ('work_section', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('supervisor_approved', models.BooleanField(default=False)),
                ('supervisor_approved_date', models.DateField(blank=True, null=True)),
                ('contracts_manager_approved', models.BooleanField(default=False)),
                ('contracts_manager_approved_date', models.DateField(blank=True, null=True)),
                ('project_director_approved', models.BooleanField(default=False)),
                ('project_director_approved_date', models.DateField(blank=True, null=True)),
                ('managing_director_approved', models.BooleanField(default=False)),
                ('managing_director_approved_date', models.DateField(blank=True, null=True)),
                ('finance_paid', models.BooleanField(default=False)),
                ('finance_paid_date', models.DateField(blank=True, null=True)),
                ('finance_comments', models.TextField(blank=True, default='')),
                ('commercial_comments', models.TextField(blank=True, default='')),
                ('contracts_manager_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cm_approved_invoices', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_invoices', to=settings.AUTH_USER_MODEL)),
                ('finance_paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_paid_invoices', to=settings.AUTH_USER_MODEL)),
                ('managing_director_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='md_approved_invoices', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invoices', to='project_admin.project')),
                ('project_director_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pd_approved_invoices', to=settings.AUTH_USER_MODEL)),
                ('supervisor_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_approved_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
