# Generated by Django 6.0.6 on 2026-07-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0014_add_user_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvoice',
            name='status',
            field=models.CharField(choices=[('bucket', 'Bucket'), ('submitted', 'Submitted')], default='submitted', max_length=20),
        ),
    ]
