# Generated by Django 6.0.6 on 2026-07-15 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0015_userinvoice_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvoice',
            name='manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinvoice',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approved_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinvoice',
            name='manager_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
