# Generated by Django 6.0.6 on 2026-07-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0016_userinvoice_manager_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalconfiguration',
            name='role_thresholds',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='approvalconfiguration',
            name='required_roles',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='approvalconfiguration',
            name='toggle_states',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
