# Generated by Django 6.0.6 on 2026-07-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0017_approvalconfiguration_role_thresholds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalconfiguration',
            name='action_type',
            field=models.CharField(choices=[('user_invoice', 'User Invoices'), ('supplier_invoice', 'Supplier Invoices'), ('variations', 'Variations'), ('purchase_order', 'Purchase Orders'), ('proforma', 'Proforma Nr Invoices'), ('user_variations_invoice', 'User Variations Invoices'), ('user_clock_in', 'User Clock in')], max_length=50),
        ),
    ]
