# Generated by Django 6.0.6 on 2026-10-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0018_alter_approvalconfiguration_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(default='GBP', max_length=10),
        ),
    ]
