# Generated by Django 6.0.6 on 2026-06-30 03:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_useraccount_assigned_projects'),
        ('super_admin', '0002_companyinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_sent', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_invoices', to='account.company')),
            ],
            options={
                'unique_together': {('company', 'year', 'month')},
            },
        ),
    ]
