# Generated by Django 6.0.6 on 2026-07-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0003_monthlyinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
