# Generated by Django 6.0.6 on 2026-08-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0004_monthlyinvoice_invoice_number_monthlyinvoice_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyinvoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
