# Generated by Django 6.0.6 on 2026-08-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0005_monthlyinvoice_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyinvoice',
            name='pdf_file',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
