# Generated by Django 6.0.6 on 2026-07-02 06:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_admin', '0004_labourbooking_loadingclearingbooking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variation_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('labour_target', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('material_target', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('claimed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_raised', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='project_admin.project')),
            ],
            options={
                'db_table': 'variations',
            },
        ),
    ]
