# Generated by Django 6.0.6 on 2026-07-04 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='date_raised',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='claimed_amount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='labour_target',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='material_target',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='variation_value',
        ),
        migrations.AddField(
            model_name='variation',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='variation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_variations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='variation',
            name='attention_of',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='variation',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='variation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_variations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='variation',
            name='description_of_works',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='variation',
            name='signed_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variation',
            name='site_instruction_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variation',
            name='submitted_to_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_sheet_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='variation',
            name='vo_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='VariationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_instruction', models.CharField(blank=True, default='', max_length=255)),
                ('work_area', models.CharField(blank=True, default='', max_length=255)),
                ('work_section', models.CharField(blank=True, default='', max_length=255)),
                ('labour', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labour_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('material', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='commercial_department.variation')),
            ],
            options={
                'db_table': 'variation_lines',
            },
        ),
    ]
