# Generated by Django 6.0.6 on 2026-07-08 03:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_department', '0002_alter_variation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_variations', to=settings.AUTH_USER_MODEL),
        ),
    ]
