# Generated by Django 6.0.6 on 2026-07-13 05:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_department', '0003_variation_assigned_users'),
        ('project_admin', '0013_variationsaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='amount_claimed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='variation',
            name='client_certified_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='variation',
            name='client_qs_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='variation',
            name='corresponding_notice_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variation',
            name='percent_claimed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='variation',
            name='valuation_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='MonthlyApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('ref_no', models.CharField(blank=True, default='', max_length=100)),
                ('retention_percentage', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('contract_works_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('variations_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_claimed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('client_certified_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_applications', to='project_admin.project')),
            ],
            options={
                'db_table': 'monthly_applications',
                'ordering': ['-application_number'],
                'unique_together': {('project', 'application_number')},
            },
        ),
    ]
