# Generated by Django 6.0.6 on 2026-07-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_department', '0004_variation_amount_claimed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='evidence_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
