# Generated by Django 6.0.6 on 2026-07-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_department', '0005_variation_evidence_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyapplication',
            name='certified_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='monthlyapplication',
            name='final_date_for_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyapplication',
            name='payment_certificate_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='monthlyapplication',
            name='payment_notice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyapplication',
            name='works_valued_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
