# Generated by Django 6.0.6 on 2026-07-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_department', '0006_add_monthly_application_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='contracts_manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variation',
            name='contracts_manager_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='fully_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variation',
            name='manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variation',
            name='manager_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='managing_director_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variation',
            name='managing_director_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='project_director_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variation',
            name='project_director_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='supervisor_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variation',
            name='supervisor_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
