# Generated by Django 6.0.6 on 2026-07-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_department', '0007_variation_contracts_manager_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='commercial_department_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variation',
            name='commercial_department_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
