# Generated by Django 6.0.6 on 2026-06-24 05:28

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('company_number', models.PositiveIntegerField(blank=True, null=True)),
                ('building_number', models.PositiveIntegerField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(blank=True, max_length=50, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_address', models.CharField(blank=True, max_length=500, null=True)),
                ('sort_code', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('iban', models.CharField(blank=True, max_length=100, null=True)),
                ('swift_bic', models.CharField(blank=True, max_length=50, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='companies/files/')),
                ('user', models.PositiveIntegerField(default=0)),
                ('projects', models.PositiveIntegerField(default=0)),
                ('activate', models.BooleanField(default=False)),
                ('monthly_subscription', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('per_user_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('auto_monthly_inv', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
