# Generated by Django 6.0.6 on 2026-06-24 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='account.company'),
        ),
    ]
