# Generated by Django 6.0.6 on 2026-06-28 05:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_useraccount_role'),
        ('project_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('project_admin', 'Project Admin'), ('managing_director', 'Managing Director'), ('document_controller', 'Document Controller'), ('commercial_manager', 'Commercial Manager'), ('procurement', 'Procurement Department'), ('contracts_manager', 'Contracts Manager'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('employee', 'Employee'), ('supplier', 'Supplier')], default='admin', max_length=30),
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supplier_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cscs_card_no', models.CharField(blank=True, max_length=50, null=True)),
                ('cscs_expiry_date', models.DateField(blank=True, null=True)),
                ('ipaf_certification', models.CharField(blank=True, max_length=100, null=True)),
                ('pasma_certification', models.CharField(blank=True, max_length=100, null=True)),
                ('sssts_smsts', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('project_admin', 'Project Admin'), ('managing_director', 'Managing Director'), ('document_controller', 'Document Controller'), ('commercial_manager', 'Commercial Manager'), ('procurement', 'Procurement Department'), ('contracts_manager', 'Contracts Manager'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('employee', 'Employee'), ('supplier', 'Supplier')], max_length=50)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='account.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='project_admin.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role_assignments',
                'unique_together': {('user', 'role', 'company', 'project')},
            },
        ),
        migrations.CreateModel(
            name='CompanySupplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eom_payment_terms', models.PositiveIntegerField(default=30, help_text='End of Month payment terms in days')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='account.company')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='account.supplierprofile')),
            ],
            options={
                'db_table': 'company_suppliers',
                'unique_together': {('company', 'supplier')},
            },
        ),
    ]
