# Generated by Django 6.0.6 on 2026-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_invitation'),
        ('project_admin', '0003_projectsubfolder_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='assigned_projects',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='project_admin.project'),
        ),
    ]
