# Generated by Django 6.0.6 on 2026-07-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_useraccount_assigned_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='categories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='digital_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employer_liability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='insurance_policy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('project_admin', 'Project Admin'), ('managing_director', 'Managing Director'), ('project_director', 'Project Director'), ('procurement_department', 'Procurement Department'), ('commercial_department', 'Commercial Department'), ('document_controller', 'Document Controller'), ('finance_department', 'Finance Department'), ('contracts_manager', 'Contracts Manager'), ('managers', 'Managers'), ('supervisor', 'Supervisor'), ('employee', 'Employee'), ('supplier', 'Supplier')], max_length=50),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('project_admin', 'Project Admin'), ('managing_director', 'Managing Director'), ('project_director', 'Project Director'), ('procurement_department', 'Procurement Department'), ('commercial_department', 'Commercial Department'), ('document_controller', 'Document Controller'), ('finance_department', 'Finance Department'), ('contracts_manager', 'Contracts Manager'), ('managers', 'Managers'), ('supervisor', 'Supervisor'), ('employee', 'Employee'), ('supplier', 'Supplier')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('project_admin', 'Project Admin'), ('managing_director', 'Managing Director'), ('project_director', 'Project Director'), ('procurement_department', 'Procurement Department'), ('commercial_department', 'Commercial Department'), ('document_controller', 'Document Controller'), ('finance_department', 'Finance Department'), ('contracts_manager', 'Contracts Manager'), ('managers', 'Managers'), ('supervisor', 'Supervisor'), ('employee', 'Employee'), ('supplier', 'Supplier')], default='admin', max_length=30),
        ),
    ]
