# Generated by Django 6.0.6 on 2026-07-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userprofile_categories_userprofile_digital_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='town',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
