# Generated by Django 6.0.6 on 2026-07-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
