# Generated by Django 6.0.6 on 2026-07-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_userprofile_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employers_liability_document',
            field=models.FileField(blank=True, null=True, upload_to='companies/insurance/'),
        ),
        migrations.AddField(
            model_name='company',
            name='employers_liability_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='employers_liability_policy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='public_liability_document',
            field=models.FileField(blank=True, null=True, upload_to='companies/insurance/'),
        ),
        migrations.AddField(
            model_name='company',
            name='public_liability_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='public_liability_policy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='utr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ni_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_document',
            field=models.FileField(blank=True, null=True, upload_to='profiles/documents/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='utr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
