# Generated by Django 6.0.6 on 2026-07-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_company_employers_liability_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='sort_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
