# Generated by Django 6.0.6 on 2026-07-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_supplierprofile_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='secondary_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('project_admin', 'Project Admin'), ('managing_director', 'Managing Director'), ('project_director', 'Project Director'), ('procurement_department', 'Procurement Department'), ('commercial_department', 'Commercial Department'), ('document_controller', 'Document Controller'), ('finance_department', 'Finance Department'), ('contracts_manager', 'Contracts Manager'), ('managers', 'Managers'), ('supervisor', 'Supervisor'), ('employee', 'Employee'), ('supplier', 'Supplier'), ('technical_department', 'Technical Department')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('project_admin', 'Project Admin'), ('managing_director', 'Managing Director'), ('project_director', 'Project Director'), ('procurement_department', 'Procurement Department'), ('commercial_department', 'Commercial Department'), ('document_controller', 'Document Controller'), ('finance_department', 'Finance Department'), ('contracts_manager', 'Contracts Manager'), ('managers', 'Managers'), ('supervisor', 'Supervisor'), ('employee', 'Employee'), ('supplier', 'Supplier'), ('technical_department', 'Technical Department')], max_length=50),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('project_admin', 'Project Admin'), ('managing_director', 'Managing Director'), ('project_director', 'Project Director'), ('procurement_department', 'Procurement Department'), ('commercial_department', 'Commercial Department'), ('document_controller', 'Document Controller'), ('finance_department', 'Finance Department'), ('contracts_manager', 'Contracts Manager'), ('managers', 'Managers'), ('supervisor', 'Supervisor'), ('employee', 'Employee'), ('supplier', 'Supplier'), ('technical_department', 'Technical Department')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('project_admin', 'Project Admin'), ('managing_director', 'Managing Director'), ('project_director', 'Project Director'), ('procurement_department', 'Procurement Department'), ('commercial_department', 'Commercial Department'), ('document_controller', 'Document Controller'), ('finance_department', 'Finance Department'), ('contracts_manager', 'Contracts Manager'), ('managers', 'Managers'), ('supervisor', 'Supervisor'), ('employee', 'Employee'), ('supplier', 'Supplier'), ('technical_department', 'Technical Department')], default='admin', max_length=30),
        ),
    ]
