# Generated by Django 6.0.6 on 2026-07-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_useraccount_secondary_role_alter_invitation_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='secondary_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('project_admin', 'Project Admin'), ('managing_director', 'Managing Director'), ('project_director', 'Project Director'), ('procurement_department', 'Procurement Department'), ('commercial_department', 'Commercial Department'), ('document_controller', 'Document Controller'), ('finance_department', 'Finance Department'), ('contracts_manager', 'Contracts Manager'), ('managers', 'Managers'), ('supervisor', 'Supervisor'), ('employee', 'Employee'), ('supplier', 'Supplier'), ('technical_department', 'Technical Department')], max_length=50, null=True),
        ),
    ]
