# Generated by Django 6.0.6 on 2026-08-15 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_userprofile_account_number_userprofile_bank_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_monthly_inv_date',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
