# Generated by Django 6.0.6 on 2026-08-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_company_auto_monthly_inv_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='auto_monthly_inv_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
