# Generated by Django 6.0.6 on 2026-08-15 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_company_auto_monthly_inv_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='auto_monthly_inv_date',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
