# Generated by Django 6.0.6 on 2026-09-07 04:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_company_auto_monthly_inv_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysupplier',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysupplier',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysupplier',
            name='invited_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='companysupplier',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_company_suppliers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companysupplier',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='companysupplier',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('declined', 'Declined'), ('revoked', 'Revoked')], default='active', max_length=20),
        ),
    ]
