# Generated by Django 6.0.6 on 2026-10-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_companysupplier_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vat_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
