# Generated by Django 6.0.6 on 2026-10-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_useraccount_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='two_factor_otp',
            field=models.CharField(blank=True, help_text='Active two-factor authentication OTP code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='two_factor_otp_backup',
            field=models.CharField(blank=True, help_text='Previous two-factor OTP to gracefully handle out-of-order delivery', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='two_factor_otp_created_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when active two-factor OTP was generated', null=True),
        ),
    ]
