# Generated by Django 6.0.6 on 2026-10-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_useraccount_two_factor_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='terms_and_conditions_document',
            field=models.FileField(blank=True, null=True, upload_to='companies/terms/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cscs_card_document',
            field=models.FileField(blank=True, null=True, upload_to='profiles/documents/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='drivers_license_document',
            field=models.FileField(blank=True, null=True, upload_to='profiles/documents/'),
        ),
    ]
