# Generated by Django 6.0.6 on 2026-07-02 06:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_admin', '0004_labourbooking_loadingclearingbooking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='project_admin.project')),
            ],
            options={
                'db_table': 'purchase_orders',
            },
        ),
        migrations.CreateModel(
            name='POCallOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_offs', to='procurement_department.purchaseorder')),
            ],
            options={
                'db_table': 'po_call_offs',
            },
        ),
    ]
