# Generated by Django 6.0.6 on 2026-07-06 06:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_userprofile_unique_together_and_more'),
        ('procurement_department', '0001_initial'),
        ('project_admin', '0005_projectvaluebooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_ref', models.CharField(max_length=50, unique=True)),
                ('variation_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_quote', models.DateField(auto_now_add=True)),
                ('quote_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('po_created', models.BooleanField(default=False)),
                ('date_po_created', models.DateField(blank=True, null=True)),
                ('procurement_comments', models.TextField(blank=True, null=True)),
                ('quote_approval_reasons', models.TextField(blank=True, null=True)),
                ('requote_comments', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL)),
                ('main_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_admin.projectfolder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='project_admin.project')),
                ('sub_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_admin.projectsubfolder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='account.companysupplier')),
            ],
            options={
                'db_table': 'quotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('per', models.CharField(blank=True, max_length=50, null=True)),
                ('each', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('comments', models.TextField(blank=True, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='procurement_department.quotation')),
            ],
            options={
                'db_table': 'quotation_line_items',
            },
        ),
    ]
