# Generated by Django 6.0.6 on 2026-07-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_department', '0003_alter_quotation_supplier_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='supplier_quote_pdf',
            field=models.FileField(blank=True, null=True, upload_to='supplier_quotes/'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='supplier_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotationlineitem',
            name='supplier_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
