# Generated by Django 6.0.6 on 2026-07-17 06:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_department', '0004_quotation_supplier_quote_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('previous_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('previous_pdf', models.FileField(blank=True, null=True, upload_to='supplier_quotes/history/')),
                ('previous_line_items', models.JSONField(default=list)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='procurement_department.quotation')),
            ],
            options={
                'db_table': 'quotation_history',
                'ordering': ['-date_recorded'],
            },
        ),
    ]
