# Generated by Django 6.0.6 on 2026-07-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_department', '0005_quotationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='commercial_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='finance_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
