# Generated by Django 6.0.6 on 2026-07-18 09:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_department', '0007_quotation_date_scheduled_quotation_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationlineitem',
            name='management_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotationlineitem',
            name='management_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrderLineCallOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_off_ref', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_call_offs', to=settings.AUTH_USER_MODEL)),
                ('called_off_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='called_off_items', to=settings.AUTH_USER_MODEL)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_offs', to='procurement_department.quotationlineitem')),
            ],
            options={
                'db_table': 'order_line_call_offs',
                'ordering': ['-date'],
            },
        ),
    ]
