# Generated by Django 6.0.6 on 2026-07-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_department', '0009_quotation_fully_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlinecalloff',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
