# Generated by Django 6.0.6 on 2026-07-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_department', '0010_orderlinecalloff_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlinecalloff',
            name='is_approved',
        ),
    ]
